defaults:
  exposed: "true"
  group: group_default
  target: "Kessel"     
  property: "INDEX_NOT_FOUND"
  update_interval: $interval_slow
  delayed_on: 0s
  delayed_off: 0s

binary_sensor:
  - platform: template
    name: ${name}
    id: ${name}
    filters:
      - delayed_on: ${delayed_on}
      - delayed_off: ${delayed_off}
    trigger_on_initial_state: true
    web_server:
      sorting_group_id: ${group}
    on_state:
      then:
        - if:
            condition:
              lambda: |-
                #if defined(ANALYTICS)
                  return getWhitelistedEntities().contains(id(${name}));
                #else
                  return false;
                #endif
            then:
              - script.execute:
                  id: mqtt_push_event
                  suffix: ${name}
                  payload: !lambda 'return x ? "On" : "Off";'

interval:
  - interval: ${update_interval}
    then:
      - lambda: |-
          if (Property::k${property} != Property::kINDEX_NOT_FOUND) {
            queueRequest(CanNode::${target}, Property::k${property});
          }

esphome:
  on_boot:
    - priority: -50
      then:
        - lambda: |-
            if (Property::k${property} != Property::kINDEX_NOT_FOUND) {
              CallbackHandler::instance().addCallback({CanNode::${target}, Property::k${property}}, [](const SimpleVariant& value){

                  bool is_on = (value.get<int>() != 0); 
                  auto binary_sensor_id{id(${name})};
                  
                  if(binary_sensor_id->state != is_on) {
                    binary_sensor_id->publish_state(is_on);
                  }
              });
            }

            #if defined(ANALYTICS)
              if(${exposed}) {
                getWhitelistedEntities().insert(id(${name}));
              }
            #endif
    - priority: -100.0
      then:
        - delay: 250ms
        - lambda: |-
            if (Property::k${property} != Property::kINDEX_NOT_FOUND) {
              queueRequest(CanNode::${target}, Property::k${property});
            }